# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afa54a07452d2bbb9f38d5b481b9ecbcebfb048286eec7a062719318d648d4910c17da8c354fe397ec072c351eea31b7c51f1a182a0e772d3590924e5437d417

test:
  secret_key_base: eba42b3200df2491135809e54af2cfa082740afe7859d520579f0ede04387ff098c0d7ef6f708a1a25ca5ac6d90e6643673bee27d07fdfdcb57259d363350a88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
