name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
      with:
        github_access_token: ${{ secrets.gh_pages_deploy_token }}
        build_configuration: production
        base_href: /Weave-Site/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/weave-site

permissions:
  contents: write

